image:https://github.com/marytts/gradle-marytts-component-plugin/actions/workflows/main.yml/badge.svg["CI", link="https://github.com/marytts/gradle-marytts-component-plugin/actions/workflows/main.yml"]
image:https://coveralls.io/repos/github/marytts/gradle-marytts-component-plugin/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/github/marytts/gradle-marytts-component-plugin?branch=master"]
image:https://img.shields.io/badge/License-LGPL%20v3-blue.svg["License: LGPL v3",link="https://www.gnu.org/licenses/lgpl-3.0"]

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:java-library-plugin: https://docs.gradle.org/current/userguide/java_library_plugin.html
:gradle: https://gradle.org/
:groovy-plugin: https://docs.gradle.org/current/userguide/groovy_plugin.html
:marytts: http://mary.dfki.de/
:mavenCentral: https://search.maven.org/
:testng: https://testng.org/

= Gradle MaryTTS Component Plugin
:toc:
:toc-placement!:
:icons: font

Utility plugin to build {marytts}[MaryTTS] components with {gradle}[Gradle].

== Plugin Usage

See https://plugins.gradle.org/plugin/de.dfki.mary.component

== Plugin behavior

To apply this plugin to a Gradle project, Gradle v6.0 or higher is recommended (although Gradle versions as low as v5.1 are compatible).

This plugin, when applied to a project, configures it as follows:

. The {java-library-plugin}[Java Library] and {groovy-plugin}[Groovy] plugins are applied
. Compatibility is set to Java 8
. The {mavenCentral}[Maven Central] repository is added, as well as DFKI's MLT repository (to resolve the JTok dependency)
. Integration tests are set up via the `integrationTest` source set and task
. Testing is enabled using {testng}[TestNG]

Specifically for MaryTTS, additional classes and resources are generated and included in the main configuration classpath:

. A service loader
. A MaryTTS config file (see <<generated-config,below>>)
. A MaryTTS component Config class
. Unit and integration tests (see <<generated-tests,below>>)

== Plugin configuration

This plugin adds a `marytts.component` extension, which is configured like this:

[source,gradle]
----
marytts {
    component {
        name = 'Hello' // <1>
        packageName = 'my.world' // <2>
    }
}
----
<1> Custom component name
<2> Custom package name

This will generate the *config* file, *service loader*, and *boilerplate Groovy and Java* source code to test and use, respectively, this component with MaryTTS:

[source]
----
build
├── generatedIntegrationTestSrc
│   └── my # <1>
│       └── world
│           └── LoadHelloIT.groovy # <2>
├── generatedSrc
│   └── my # <1>
│       └── world
│           └── HelloConfig.java # <2>
└── generatedTestSrc
    └── my # <1>
        └── world
            └── HelloConfigTest.groovy # <2>
----
<1> Custom package path
<2> Class names derived from custom component name

=== YAML configuration

Since many MaryTTS components require detailed configuration, the configuration can be externalized into a YAML resource, like this:

[source,gradle]
----
marytts {
    component {
        config from: 'config.yaml' // <1>
    }
}
----
<1> YAML config source

IMPORTANT: If a YAML file is specified, it must be readable and valid, otherwise Gradle will fail to configure the project!

[source,yaml]
----
# A comment

locale: xy

foo:
    bar: foo baz # <1>

    qux: # <2>
    - quux
    - quuux

    fnord: 'jar:/path/to/the/fnord' # <3>
----
<1> Nested config keys will be flattened.
<2> A list will be converted to a config property with a trailing `.list`.
<3> A value with a `jar:` prefix (which should be quoted in YAML) will be treated as a classpath resource when the component runs in MaryTTS.

=== Generated config
[[generated-config]]

The above YAML config will generate a configuration like this:

[source]
----
locale = xy
foo.bar = foo baz
foo.qux.list = \
    quux \
    quuux
foo.fnord = jar:/path/to/the/fnord
----

=== Generated test code
[[generated-tests]]

Groovy source code for unit and integration testing with {testng}[TestNG] will be generated to verify that the component can be loaded, and that all configured properties have the expected values.
Any resources will be loaded as streams to ensure they exist on the classpath.

.HelloConfigTest.groovy
[source,groovy]
----
package my.world

import marytts.config.*
import org.testng.annotations.*

class HelloConfigTest {

    HelloConfig config

    @BeforeMethod
    void setup() {
        config = new HelloConfig()
    }

    @Test
    public void isNotMainConfig() {
        assert config.isMainConfig() == false
    }

    @Test
    public void testConfigBaseClass() {
        assert config instanceof LanguageConfig
    }

    @Test
    public void canGetProperties() { // <1>
        assert config.properties.'locale' == 'xy'
        assert config.properties.'foo.bar' == 'foo baz'
        assert config.properties.'foo.qux.list'.tokenize().containsAll(['quux', 'quuux'])
        assert config.properties.'foo.fnord' == 'jar:/path/to/the/fnord'
    }
}
----
<1> Assertions generated from config

.LoadHelloIT.groovy
[source,groovy]
----
package my.world

import marytts.server.MaryProperties
import marytts.util.MaryRuntimeUtils

import org.testng.annotations.*

class LoadHelloIT {

    @BeforeMethod
    void setup() {
        MaryRuntimeUtils.ensureMaryStarted()
    }

    @DataProvider
    Object[][] properties() {
        [ // <1>
            ['foo.bar', 'foo baz'],
            ['foo.qux.list', ['quux', 'quuux']],
            ['foo.fnord', 'jar:/path/to/the/fnord']
        ]
    }

    @Test(dataProvider = 'properties')
    public void canGetProperty(name, expected) {
        def actual
        switch (name) {
            case ~/.+\.list$/:
                actual = MaryProperties.getList(name)
                assert actual.containsAll(expected)
                break
            default:
                actual = MaryProperties.getProperty(name)
                assert expected == actual
                break
        }
        if ("$expected".startsWith('jar:')) {
            assert MaryProperties.getStream(name)
        }
    }
}
----
<1> Parameterized tests generated from config
