name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build --warning-mode all
